//
// Created by Asus on 10/17/2025.
//

#ifndef INC_1_ASYMPTOTIC_ANALYSIS_SUM_OF_FIRST_N_NATURAL_NUMBERS_H
#define INC_1_ASYMPTOTIC_ANALYSIS_SUM_OF_FIRST_N_NATURAL_NUMBERS_H



class Sum_Of_First_N_Natural_Numbers {

};



#endif //INC_1_ASYMPTOTIC_ANALYSIS_SUM_OF_FIRST_N_NATURAL_NUMBERS_H
